env:
  global:
    - CONDA_PREFIX=$HOME/miniconda
    - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
os:
  - linux
  - osx
sudo: False

language: python

python:
  - "2.7"
  # - "3.5"
  - "3.6"
  # - "3.7"

before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:


  - echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
  - |
    if [[ $TRAVIS_OS_NAME == "osx"]]; then
      brew remove --force $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
    fi
  - pip install --upgrade pip

install:
  - echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
  - pip install anticipy

script:
  - python -m unittest discover
